[tool.poetry]
authors = ["Brenden Matthews <brenden@brndn.io>"]
description = "ThetaGang is an IBKR bot for getting money"
documentation = "https://github.com/brndnmtthws/thetagang/blob/master/README.md"
homepage = "https://github.com/brndnmtthws/thetagang"
license = "AGPL-3.0-only"
name = "thetagang"
readme = "README.md"
repository = "https://github.com/brndnmtthws/thetagang.git"
version = "0.1.20"

[tool.poetry.dependencies]
click = "^7.1.2"
click-log = "^0.3.2"
colorama = "^0.4.4"
ib_insync = "^0.9.64"
python = "^3.7"
python-dateutil = "^2.8.1"
pytimeparse = "^1.1.8"
schema = "^0.7.3"
toml = "^0.10.2"

[tool.poetry.dev-dependencies]
autoflake = "^1.4"
autohooks = "^2.2.0"
autohooks-plugin-black = "^1.2.0"
autohooks-plugin-isort = "^1.0.0"
black = "^20.8b1"
isort = "^5.6.4"
pylint = "^2.6.0"
pytest = "^6.1.2"

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/brndnmtthws/thetagang/issues"
"GitHub" = "https://github.com/brndnmtthws/thetagang"

[tool.poetry.scripts]
thetagang = 'thetagang.entry:cli'
vscode = "vscode:vscode"

[tool.pylint.messages_control]
disable = "C0330, C0326"

[tool.pylint.format]
max-line-length = "88"

[tool.isort]
ensure_newline_before_comments = true
force_grid_wrap = 0
include_trailing_comma = true
line_length = 88
multi_line_output = 3
use_parentheses = true

[tool.autohooks]
mode = "poetry"
pre-commit = ["autohooks.plugins.isort", "autohooks.plugins.black"]

[build-system]
build-backend = "poetry.masonry.api"
requires = ["poetry>=0.12"]
